name: 'McNative-Test-Plugin'
category: 'Testing'
uniqueId: 'UniqueId'
version: '1.0.0'
main: 'net.prematic.mcnative.testplugin.service.TestPlugin'
description: 'Demo and test plugin'
website: 'https://mcnative.prematic.net'
author: 'Davide Wietlisbach'
authors: ["",""]



depends: ['DKCoins', 'DKBans']
softdepends: ['DKCoins', 'DKBans']
loadbefore: ['McNative']