main: 'org.mcnative.runtime.bukkit.BukkitMcNativeBootstrap'
name: 'McNative'
version: '1.0.0'
description: 'McNative is a framework for creating cross platform Minecraft applications. McNative supports Minecraft Java Edition 1.7 to 1.14 and Bedrock edition 1.12 to 1.12'
website: 'https://mcnative.org'
authors: ['Pretronic']
softdepend: ['PlaceholderAPI','Vault','CloudNetAPI','CloudNet-Bridge','ViaVersion','ProtocolLib']
